spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        default_schema: enrollmentdbdev

server:
  port: 7070