# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

server:
  servlet:
    context-path: /api/enroll-management
  error:
    whitelabel:
      enabled: false