# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: AngelF905

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: enrollmentdb
        jdbc.lob.non_contextual_creation: true

